// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  float light_rot_angle = (2 * M_PI * animation_seconds) / 8;  

  mat4 Rmat = mat4(
    cos(light_rot_angle), 0, -sin(light_rot_angle), 0,
    0, 1, 0, 0,
    sin(light_rot_angle), 0, cos(light_rot_angle), 0,
    0, 0, 0, 1);
	
  vec3 vector_from_surface_to_cam = -((view * view_pos_fs_in).xyz);
  vec3 light_dir = (view * Rmat * vec4(1, 0.5, 0, 0)).xyz;
  vec3 surface_normal = normalize(normal_fs_in);

  vector_from_surface_to_cam = normalize(vector_from_surface_to_cam);
  light_dir = normalize(light_dir);

  float noise = (perlin_noise(4 * sphere_fs_in) + 1) * 4;
  noise = abs(noise);  

  // full spec
  vec3 ks = vec3(1.0, 1.0, 1.0);

  // shininess
  int p = 800;

  // grey moon or blue planet
  vec3 kd, ka;
  if(is_moon){
    kd = vec3(0.5, 0.5, 0.5) * noise;
    ka = vec3(0.10, 0.10, 0.10);
  } else{
    kd = vec3(0.1, 0.2, 0.7) * noise;
    ka = vec3(0.05, 0.2, 0.35);
  }

  color = blinn_phong(ka, kd, ks, p, surface_normal, vector_from_surface_to_cam, light_dir); 
}
